### ISSUE TITLE
It' not allow with direct and proxy access, PHP Fatal error:  Uncaught Exception: Trust X-Forwarded-For Extension

### ISSUE THREAD

**Issue by alphaonex86** [marttiphpbb/phpbb-ext-trustxforwardedfor#1]
in ext/marttiphpbb/trustxforwardedfor/event/listener.php on line 61
[31-Jan-2020 23:13:23 UTC] PHP Fatal error:  Uncaught Exception: Trust X-Forwarded-For Extension: invalid X-Forwarded-For:  in ext/marttiphpbb/trustxforwardedfor/event/listener.php:61

**Comment by eeemarv** [comment]
The `X-Forwarded-For` header must be set by your reverse proxy server.

**Comment by marttiphpbb** [comment]
The `X-Forwarded-For` header must be set by your reverse proxy.

**Comment by alphaonex86** [comment]
When my phpBB is visited with IPv6 is without proxy. When it visited via IPv4 is via proxy.

**Comment by marttiphpbb** [comment]
Why do you have such a setup?

**Comment by alphaonex86** [comment]
Due to lack of IPv4. We have a /32 ipv6 but only a /24 public IPv4.

**Comment by marttiphpbb** [comment]
Sorry, I don't understand that. What is "only a /24 public IPv4"?

**Comment by alphaonex86** [comment]
It's the most used way to expose IPv6 space to IPv4.

**Comment by marttiphpbb** [comment]
That doesn't make sense to me. We're talking about a **reverse** proxy, right? Do you have a link to a tutorial or something that describes the setup?

**Comment by marttiphpbb** [comment]
The point of the reverse proxy is that it handles all the traffic from the public net  (caching, gzip comression, ssl, url rewriting, load balancing, logging), so it takes of load from the web server.

**Comment by alphaonex86** [comment]
![ipv6-only-webserver-from-ipv4](https://user-images.githubusercontent.com/778581/73610915-ecf20280-45b2-11ea-888a-218d48dccbd9.png)

**Comment by marttiphpbb** [comment]
So why not route all traffic trough the reverse proxy? Then the setup is the same for all clients. Anyway, that's how the extension is meant to be used. It only allows request with a `X-Forwarded-For` header.

**Comment by alphaonex86** [comment]
Because reverse proxy have limitation (concurrent connection, http, ...), it's just a work around. Some customer have fine tunned http server where reverse proxy break this fine tunning.

I have modification your extension to my usage, if you are interested I do a clean and I do a push request.

**Comment by marttiphpbb** [comment]
Well, it is a security measure of this extension not to allow any other traffic than from the reverse proxy and I like to keep it that way. You can of course just publish your forked version as you like.
